### ISSUE TITLE
SAP HANA Connector: POST failed with 500 Error Code

### ISSUE THREAD

**Issue by psivagur** [yangzhaox/loopback-connector-saphana#1]
I created a REST API for sap hana connector and while trying POST, the REST call failed with HTTP Error Code 500.

Response Body:

{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "invalid sequence: CONTACTSeq: line 1 col 26 (at pos 25)",
    "code": 313,
    "sqlState": "HY000",
    "level": 1,
    "position": 25
  }
}

where  CONTACT is my model name.

I tried PUT, GET,DELETE, and it worked fine. Only POST call is failing with above error.

**Comment by yzx396** [comment]
Could you please check if the sequence CONTACTSeq is created or not in HANA?
