### ISSUE TITLE
executeSQL() should be implemented by Connector

### ISSUE THREAD

**Issue by RevanthNy** [yangzhaox/loopback-connector-saphana#3]
some of  tests provided in the test folder are failing, due to the error executeSQL() should be implemented by the connector. Although the implementation is same as SAPHANA.prototype.query method may be I think the method name should be changed. Once after changing the method name it shows callback should be function error.

Has anyone got this error previously. Anyone who established connection to HANA with this connector and able to make operations in the database??

**Comment by oinuar** [comment]
Yes, this connector is in production use and it implements LoopBack connector interface. Please see https://loopback.io/doc/en/lb3/Defining-data-sources.html how to configure LoopBack to use it. However, there are some issues and especially tests may be deprecated. Pull requests are welcome.
